# Generated by Django 2.1.1 on 2020-03-17 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Account_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('Name', models.CharField(default='홍길동', max_length=20)),
                ('PhoneNumber', models.CharField(default='01000000000', max_length=20)),
                ('User_Status', models.IntegerField(default=1, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Notice_UpdateTime', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 18, 15, 54, 36470))),
                ('Title', models.CharField(default='제목', max_length=30)),
                ('Detail', models.TextField(null=True)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Product_No', models.CharField(max_length=30, unique=True)),
                ('Product_Name', models.CharField(default='상품명', max_length=30)),
                ('ImageURL', models.TextField(null=True)),
                ('DetailImage', models.TextField(null=True)),
                ('Max_Num', models.IntegerField(default=10)),
                ('Size', models.IntegerField(default=36)),
                ('Width_Spring', models.IntegerField(default=6)),
                ('IsRecommand', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=1000)),
                ('IsPublic', models.IntegerField(default=1)),
                ('Company_Name', models.CharField(default='venduster', max_length=100)),
                ('Owner_Username', models.ForeignKey(default='manager', on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Vending_Machine',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('VM_No', models.CharField(max_length=30, unique=True)),
                ('VM_Name', models.CharField(default='자판기별명', max_length=30)),
                ('Longitude', models.TextField(null=True)),
                ('Latitude', models.TextField(null=True)),
                ('Address', models.TextField(null=True)),
                ('TotalCount', models.IntegerField(default=0)),
                ('TotalSales', models.IntegerField(default=0)),
                ('Firmware_Version', models.FloatField(default=1.0, null=True)),
                ('IsSelling', models.BooleanField(default=True)),
                ('IsWorking', models.IntegerField(default=0)),
                ('VM_IsEmpty', models.BooleanField(default=False)),
                ('StartTime', models.TimeField(default=datetime.time(7, 0))),
                ('EndTime', models.TimeField(default=datetime.time(0, 0))),
                ('UpdateTime', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 18, 15, 54, 32796))),
                ('Model_Num', models.CharField(default='1111', max_length=30)),
                ('Error', models.CharField(max_length=20)),
                ('Max_Product_Cell', models.IntegerField(null=True)),
                ('Body_Size', models.TextField(null=True)),
                ('ImageURL', models.TextField(null=True)),
                ('Display_Size', models.TextField(null=True)),
                ('InternetCheck', models.BooleanField(default=True)),
                ('CityName', models.CharField(default='경기도', max_length=50, null=True)),
                ('Owner_Username', models.ForeignKey(default='iot_vm', on_delete=django.db.models.deletion.CASCADE, related_name='Owner_Username', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('Supplier_Username', models.ForeignKey(default='iot_vm', on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Username', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'vending_machine',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Video_No', models.IntegerField(unique=True)),
                ('Video_URL', models.TextField(null=True)),
                ('title', models.CharField(default='제목', max_length=30)),
                ('thumbnail', models.TextField(null=True)),
                ('VideoUpdateTime', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 18, 15, 54, 34297))),
                ('Account_Id', models.ForeignKey(default='1111', on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VM_Product',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('UI_No', models.IntegerField(default=2, unique=True)),
                ('Current_Num', models.IntegerField(default=0)),
                ('IsEmpty', models.BooleanField(default=False)),
                ('DiscountedPrice', models.IntegerField(default=0)),
                ('DueDiscountPrice', models.DateTimeField(blank=True, null=True)),
                ('ProductUpdateTime', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 18, 15, 54, 35747))),
                ('IsPromotioned', models.BooleanField(default=0)),
                ('IsChecked', models.IntegerField(default=0)),
                ('IsPrivate', models.BooleanField()),
                ('Product_No', models.ForeignKey(default='test001', on_delete=django.db.models.deletion.CASCADE, to='app.Product', to_field='Product_No')),
                ('VM_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vending_Machine', to_field='VM_No')),
            ],
            options={
                'db_table': 'vm_product',
            },
        ),
        migrations.CreateModel(
            name='VM_Product_Tray',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Tray_No', models.TextField(default='A')),
                ('UpdateTime', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 18, 15, 54, 36987))),
                ('Quantity', models.IntegerField(default=1)),
                ('Cell_No_Id', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.VM_Product', to_field='UI_No')),
                ('VM_No_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vending_Machine', to_field='VM_No')),
            ],
            options={
                'db_table': 'vm_product_tray',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Video_No',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Video', to_field='Video_No'),
        ),
    ]
